/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KomixJahe.Frame;

/**
 *
 * @author USER
 */
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import KomixJahe.Koneksi.*;
import KomixJahe.Other.*;
import KomixJahe.Pegawai.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class FrmPegawai extends javax.swing.JFrame {

    /**
     * Creates new form FrmPetugas
     */
    public FrmPegawai() {
        initComponents();
        tampilkanData();
        kosongkanForm();
    }
      public void kosongkanForm()
    {
    
        idPegawai.setText("0");
        Nama.setText("");
        jk.setText("");
        StatusPegawai.setText("");
        StatusKawin.setText("");
        Alamat.setText("");
        Telp.setText("");
        Jabatan.setText("");
    }
       public void tampilkanData()
    {
        String [] kolom = {"ID", "Nama Pegawai", "Jenis Kelamin","Status Pegawai", "Status Pernikahan", "Alamat", "Telepon", "Jabatan"};
        ArrayList<Pegawai> list = new Pegawai().getAll();
        Object rowData[] = new Object[8];
        
        tblPetugas.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Pegawai pg : list)
        {
            rowData[0] = pg.getIdpegawai();
            rowData[1] = pg.getNama();
            rowData[2] = pg.getJeniskelamin();
            rowData[3] = pg.getStatuskepegawaian();
            rowData[4] = pg.getStatusperkawinan();
            rowData[5] = pg.getAlamat();
            rowData[6] = pg.getTelepon();
            rowData[7] = pg.getJabatan();
            
            ((DefaultTableModel)tblPetugas.getModel()).addRow(rowData);
        }
    }
    public void cari(String keyword){
        String[] kolom = {"ID", "Nama Pegawai", "Jenis Kelamin","Status Pegawai", "Status Pernikahan", "Alamat", "Telepon", "Jabatan"};
        ArrayList<Pegawai> list = new Pegawai().search(keyword);
        Object rowData[] = new Object[8];
        
        tblPetugas.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Pegawai p : list)
        {
            rowData[0] = p.getIdpegawai();
            rowData[1] = p.getNama();
            rowData[2] = p.getJeniskelamin();
            rowData[3] = p.getStatuskepegawaian();
            rowData[4] = p.getStatusperkawinan();
            rowData[5] = p.getAlamat();
            rowData[6] = p.getTelepon();
            rowData[7] = p.getJabatan();
            
            ((DefaultTableModel) tblPetugas.getModel()).addRow(rowData);
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idPegawai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        StatusKawin = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Telp = new javax.swing.JTextField();
        Jabatan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambahBaru = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetugas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        StatusPegawai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Pegawai");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jLabel2.setText("Jenis Kelamin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        idPegawai.setEditable(false);
        idPegawai.setToolTipText("");
        getContentPane().add(idPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 82, 196, -1));

        jLabel3.setText("Status Pegawai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        jLabel4.setText("Status Perkawinan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, -1, -1));

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, -1, -1));

        jLabel6.setText("No. Telp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, -1, -1));

        jLabel7.setText("Jabatan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 349, -1, -1));
        getContentPane().add(StatusKawin, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 230, 196, -1));
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 268, 196, -1));
        getContentPane().add(Telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 306, 196, -1));
        getContentPane().add(Jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 346, 251, -1));

        jLabel8.setBackground(new java.awt.Color(255, 0, 102));
        jLabel8.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel8.setText("       PANTI ASUHAN sLANKERS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 445, 65));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 387, 100, -1));

        btnTambahBaru.setText("Tambah Baru");
        btnTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 421, 150, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 243, -1));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        tblPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPetugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPetugas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 752, -1));

        jLabel9.setText("Nama");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 120, 196, -1));
        getContentPane().add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 154, 196, -1));
        getContentPane().add(StatusPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 192, 196, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 82, -1, -1));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Pegawai pg = new Pegawai();
        pg.setIdpegawai(Integer.parseInt(idPegawai.getText()));
        pg.setNama(Nama.getText());
        pg.setJeniskelamin(jk.getText());
        pg.setStatuskepegawaian(StatusPegawai.getText());
        pg.setStatusperkawinan(StatusKawin.getText());
        pg.setAlamat(Alamat.getText());
        pg.setTelepon(Telp.getText());
        pg.setJabatan(Jabatan.getText());
        pg.save();
        idPegawai.setText(Integer.toString(pg.getIdpegawai()));
        tampilkanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblPetugas.getModel();
        int row = tblPetugas.getSelectedRow();
        
        Pegawai pg = new Pegawai().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        pg.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahBaruActionPerformed

    private void tblPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPetugasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblPetugas.getModel();
        int row = tblPetugas.getSelectedRow();
        
        idPegawai.setText(model.getValueAt(row, 0).toString());
        Nama.setText(model.getValueAt(row, 1).toString());
        jk.setText(model.getValueAt(row, 2).toString());
        StatusPegawai.setText(model.getValueAt(row, 3).toString());
        StatusKawin.setText(model.getValueAt(row, 4).toString());
        Alamat.setText(model.getValueAt(row, 5).toString());
        Telp.setText(model.getValueAt(row, 6).toString());
        Jabatan.setText(model.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tblPetugasMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         cari(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.hide();
        FromMenu fm = new FromMenu();
        fm.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Jabatan;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField StatusKawin;
    private javax.swing.JTextField StatusPegawai;
    private javax.swing.JTextField Telp;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JTextField idPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jk;
    private javax.swing.JTable tblPetugas;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
